### ISSUE TITLE
Duplicate methods for `lastUpdateCheck` in settings.js

### ISSUE THREAD

**Issue by Marcono1234** [mojira/message-extension#14]
It appears there are duplicate methods for setting and getting `lastUpdateCheck`:
https://github.com/mojira/message-extension/blob/336102e51d0babc6093dfaf616a7ba3bfa8eaa44/src/util/settings.js#L121-L130
https://github.com/mojira/message-extension/blob/336102e51d0babc6093dfaf616a7ba3bfa8eaa44/src/util/settings.js#L143-L152

Is this intended? Or are `setLastUpdate` and `getLastUpdate` supposed to apply to a different setting?

**Comment by violine1101** [comment]
`lastUpdateCheck` is the last time the extension checked for an update. `lastUpdate` is only set when the helper messages actually change (i.e. there was an update to the `helper-messages` repo).
