### ISSUE TITLE
Add message button doesn't appear in v2 release

### ISSUE THREAD

**Issue by Greymagic27** [mojira/message-extension#17]
On my main PC I can see that the box has a green outline, but the message list won't appear. The shortcuts still work however.

On my laptop I can't see the green outline and the messages don't show up at all. I've tried reinstalling it several times with several restarts to the browser.

EDIT: The messages button appears on the resolve screen. Also noticed no account issue message for MCL :P

EDIT2: The issues I report always seem to go away after I report them, everything is working fine on my main PC now. I've not been back on my laptop yet so not sure about that. 

Saying that, it's no longer on the comment box anymore, just on the resolve box.

**Comment by violine1101** [comment]
I had some similar issues as well, wondering whether it has something to do with the automatic update.

**Comment by O5X** [comment]
Yea.  It didn't auto update for me for whatever reason

**Comment by O5X** [comment]
It came up that it needed an update today, but now even the shortcuts aren't working.

**Comment by O5X** [comment]
Debug console output: https://imgur.com/a/3ce0gai

**Comment by O5X** [comment]
It seems to be working fine for me now on my main PC, not tried on my laptop yet.

**Comment by O5X** [comment]
It seems to work 90% of the time now. When it's not working it usually fixes after rebooting the PC

**Comment by violine1101** [comment]
I've pushed some changes to error reporting now; if the issue still occurs in v0.3 (will be released later today), please file a new issue with the error message shown via the popup of the extension icon (and there should be more info in the console too if an error is thrown).
