### ISSUE TITLE
Cannot add certain messages from dropdown when using Waterfox

### ISSUE THREAD

**Issue by violine1101** [mojira/message-extension#22]
When using Waterfox, selecting some messages (notably duplicate) from the dropdown doesn't paste them into the text field.

**Comment by SunCatMC** [comment]
it might be important that it's on linux

**Comment by SunCatMC** [comment]
it happens for all of the messages that require a ticket number in the message (all of the duplicates without set number)

**Comment by SunCatMC** [comment]
and happens with WAI

**Comment by NeunEinser** [comment]
WAI also has a parameter for the WAI reason.

**Comment by violine1101** [comment]
Okay, that's good to know. Perhaps there's some issue with Waterfox preventing access to the clipboard or something.

**Comment by SunCatMC** [comment]
does not expand

**Comment by SunCatMC** [comment]
What about adding a fail-safe for now of putting the text anyway and add smth like "PASTE" instead of the text from the clipboard?
