### ISSUE TITLE
Add a filter for different projects

### ISSUE THREAD

**Issue by O5X** [mojira/message-extension#4]
This would be helpful since we can easily and quickly find the message we're looking for, either by project filters like on the helper messages webpage or by a search feature.

(I've never made an extension so there may be limitations to what can be done)

**Comment by O5X** [comment]
I've actually just taken a look at it looks like it's already doing this? If so feel free to close aha

**Comment by violine1101** [comment]
Yeah, thankfully JIRA is so nice to directly include the ticket ID in an attribute of the text field, so the project is extracted from there and only relevant messages are shown 😄
