### ISSUE TITLE
MC-297 message is in the wrong place

### ISSUE THREAD

**Issue by O5X** [mojira/message-extension#5]
For the MC project the 'duplicate of MC-297' message is at the top of the list. This message should be located under 'duplicate of MC-128302' message as all other messages are following the same order as the helper messages website.

**Comment by violine1101** [comment]
This is because it's the only message that has a number-only shortcut, and JavaScript always sorts those on top.

This can be fixed, but how should it sort the messages? Should it sort them by the full key? By the shortcut? By the name?

**Comment by O5X** [comment]
Whatever the helper message website sorts it by if that's possible. Just so it's in the same order as that :P

**Comment by violine1101** [comment]
Fixed in 7319b9ec9c66a43fbafe5da405c314b1c2d972bb; the dropdown items now are sorted lexicographically, which is still not perfect (it sorts MC-128302 before MC-297, for instance), but it's better than it was before.
