### ISSUE TITLE
Unable to load extension - "lib/browser-polyfill.min.js" missing

### ISSUE THREAD

**Issue by DrAwesome4333** [mojira/message-extension#51]
When attempting to load version 0.4 on Chrome, it comes up with the error:
_Could not load javascript 'lib/browser-polyfill.min.js' for content script._

There is no lib folder in the extension pack.

**Comment by violine1101** [comment]
That's very peculiar, the file is inside of the zip attached to the v0.4 release. Did you build the extension from source?

**Comment by DrAwesome4333** [comment]
The zip folder I down loaded last week was missing the files. I redownloaded the folder and it has them. I am not sure if this was user error, or GitHub having some problems, but the issue seems to be resolved now.

**Comment by violine1101** [comment]
Ah, perhaps you accidentally downloaded "source code", the lib folder is indeed missing there because it's not part of this project.
