### ISSUE TITLE
Messages won't allow you to send unless you update the message yourself

### ISSUE THREAD

**Issue by O5X** [mojira/message-extension#6]
If you put any message as a comment, the 'add' button will be greyed out until you make an edit of your own.

This is slightly different on the resolve screen where it won't allow you to click on a custom message until you've made an edit there yourself

**Comment by O5X** [comment]
This is slightly different on the resolve screen where it won't allow you to click on a custom message until you've made an edit there yourself

**Comment by O5X** [comment]
It also seems to a bit wacky to reproduce. I can paste messages in fine now, maybe because I've done it once already?

**Comment by violine1101** [comment]
If the field is empty and you use the button to insert the message, the "Add" button doesn't get activated, probably because it listens for key press events, and inserting a message with the button doesn't send one. If you use the shortcuts, it works fine.

**Comment by O5X** [comment]
Yea. The shortcuts are awesome!
