### ISSUE TITLE
mji-tdup sends the duplicate message as well as the technical one

### ISSUE THREAD

**Issue by O5X** [mojira/message-extension#9]
This also happens with mji-fdup, mji-wdup.

It also looks like it happens with mji-pdup but in a slightly different way. It sends one duplicate message but the private bit gets shoved below the quick links. It also seems to send two quick links.

**Comment by violine1101** [comment]
I'm unable to reproduce this. Did you change the prefix to an empty string?

**Comment by O5X** [comment]
It's still mji-, I've not edited any settings since I installed it. Seems to have resolved itself though. I'll see if I can repro at all now

**Comment by O5X** [comment]
Can't reproduce anymore so I'm closing the issue.
